EVALUATE
CALCULATETABLE(
    SUMMARIZECOLUMNS(
        dim_mortmgr[MortMgrName],
        dim_funding_channel_type[FundingChannelTypeName],
        "% sent", DIVIDE([Documents sent], CALCULATE([Documents sent], REMOVEFILTERS(dim_funding_channel_type[FundingChannelTypeName]), REMOVEFILTERS(dim_mortmgr))),
        "hh:mm:ss", [Average Business Hours to Send Processed Documents]
    ),
    dim_mortmgr[MortMgrName] IN { "P&N Bank", "BCU Bank" },
    dim_funding_channel_type[FundingChannelTypeName] IN { "Direct", "Broker" }
)